const types = {
  TOGGLE_PLAYING_FLAG: "TOGGLE_PLAYING_FLAG",
  CREATE_ROOM: "CREATE_ROOM",
  SET_PIECE: "SET_PIECE",
  RESET_GAME: "RESET_GAME",
  START_NEW_ROUND: "START_NEW_ROUND",
  SET_SCORE: "SET_SCORE",
  PUBLISH_MOVE: "PUBLISH_MOVE",
  TOGGLE_GAME_BOARD: "TOGGLE_GAME_BOARD",
  SET_USER_INFO: "SET_USER_INFO",
  TOGGLE_LOGIN_STATE: "TOGGLE_LOGIN_STATE",
};

export default types;
